# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sun Jul 12 12:14:41 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

"""

Must Do:

1. Reference to Frame_Tasklist frame.
2. Getter and setter methods to pass data from Frame_Tasklist frame.

"""
class Dialog_Add_Edit_Task(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog_Add_Edit_Task.__init__
        kwds["style"] = kwds.get("style", 0)
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((515, 315))
        self.text_ctrl_taskdescription = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_datecreated = wx.TextCtrl(self, wx.ID_ANY, "")
        self.text_ctrl_datedone = wx.TextCtrl(self, wx.ID_ANY, "")
        self.checkbox_done = wx.CheckBox(self, wx.ID_ANY, "Done")
        self.button_ok = wx.Button(self, wx.ID_ANY, "Ok")
        self.button_cancel = wx.Button(self, wx.ID_ANY, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_ok_click, self.button_ok)
        self.Bind(wx.EVT_BUTTON, self.button_cancel_click, self.button_cancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog_Add_Edit_Task.__set_properties
        self.SetTitle("Operation")
        self.SetSize((515, 315))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Dialog_Add_Edit_Task.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.WrapSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        label_operation = wx.StaticText(self, wx.ID_ANY, "label_1adsfasfasfasdfadsadfs")
        label_operation.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_5.Add(label_operation, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        label_taskdescription = wx.StaticText(self, wx.ID_ANY, "Task Description")
        sizer_7.Add(label_taskdescription, 0, wx.ALL, 10)
        sizer_7.Add(self.text_ctrl_taskdescription, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        label_datecreated = wx.StaticText(self, wx.ID_ANY, "Date Created")
        grid_sizer_1.Add(label_datecreated, 0, wx.ALIGN_RIGHT | wx.ALL, 10)
        grid_sizer_1.Add(self.text_ctrl_datecreated, 0, 0, 0)
        label_datedone = wx.StaticText(self, wx.ID_ANY, "Date Done")
        grid_sizer_1.Add(label_datedone, 0, wx.ALIGN_RIGHT | wx.ALL, 10)
        grid_sizer_1.Add(self.text_ctrl_datedone, 0, 0, 0)
        sizer_5.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_5.Add(self.checkbox_done, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        label_status = wx.StaticText(self, wx.ID_ANY, "label_1")
        label_status.SetFont(wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_5.Add(label_status, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)
        sizer_6.Add(self.button_ok, 0, 0, 0)
        sizer_6.Add(self.button_cancel, 0, 0, 0)
        sizer_5.Add(sizer_6, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_5)
        self.Layout()
        # end wxGlade

    def button_ok_click(self, event):  # wxGlade: Dialog_Add_Edit_Task.<event_handler>
        #print("Event handler 'button_ok_click' not implemented!")
        #event.Skip()

        self.Close()

    def button_cancel_click(self, event):  # wxGlade: Dialog_Add_Edit_Task.<event_handler>
        #print("Event handler 'button_cancel_click' not implemented!")
        #event.Skip()

        self.Close()

# end of class Dialog_Add_Edit_Task
