# -*- coding: UTF-8 -*-
#
# Author: Ryan Baclit
# Email: gamehelphere@gmail.com
#
# generated by wxGlade 0.9.6 on Sun Jul  5 17:28:04 2020
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Frame_Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frame_Main.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.button_start = wx.Button(self, wx.ID_ANY, "Start")
        self.button_about = wx.Button(self, wx.ID_ANY, "About")
        self.button_exit = wx.Button(self, wx.ID_ANY, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_start_click, self.button_start)
        self.Bind(wx.EVT_BUTTON, self.button_about_click, self.button_about)
        self.Bind(wx.EVT_BUTTON, self.button_exit_click, self.button_exit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Frame_Main.__set_properties
        self.SetTitle("Generic Task Program")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frame_Main.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        label_title = wx.StaticText(self, wx.ID_ANY, "Generic Task Program\n")
        label_title.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(label_title, 12, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 19)
        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 7)
        label_selectoption = wx.StaticText(self, wx.ID_ANY, "Select an option")
        sizer_1.Add(label_selectoption, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 21)
        sizer_1.Add(self.button_start, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.button_about, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.button_exit, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        label_version = wx.StaticText(self, wx.ID_ANY, "Version 1.0")
        sizer_1.Add(label_version, 0, wx.ALL, 10)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def button_start_click(self, event):  # wxGlade: Frame_Main.<event_handler>
        print("Event handler 'button_start_click' not implemented!")
        event.Skip()

    def button_about_click(self, event):  # wxGlade: Frame_Main.<event_handler>
        print("Event handler 'button_about_click' not implemented!")
        event.Skip()

    def button_exit_click(self, event):  # wxGlade: Frame_Main.<event_handler>
        print("Event handler 'button_exit_click' not implemented!")
        event.Skip()

# end of class Frame_Main
